### PR TITLE
Add test data for hp-socket

### PR DESCRIPTION
**Pull request by Still34**
Related PR https://github.com/mandiant/capa-rules/pull/848

### CODE REVIEW

**Comment by williballenthin** [comment]
CI tests warn this file takes a while to analyze (5 minutes?). @Still34 do you think it's feasible to find a smaller sample or is this the best we'll get?

i can poke around on VT later today, too.

**Comment by Still34** [comment]
Unfotunately this is the only green sample I know of. Technically you can replace the sample with something like the official compiled demo/test files, and it'll match too - it just won't be matching a necessarily malicious file.

**Comment by williballenthin** [comment]
thanks!

**Comment by Still34** [comment]
Huh, weird, vivisect is having a bit of a problem with the ELF. I'll look into it.

**Comment by Still34** [comment]
Yeah I'm struggling to find a sample that'll play nice with the CI pipeline. Any help?

**Comment by williballenthin** [comment]
no problem!

i will take look around on VT and/or we can make an exception here. though, i'll be afk for a couple days - hope that's no problem, just know im not ignoring this thread!

**Comment by mr-tz** [comment]
I can try to find a sample next week.

**Comment by mr-tz** [comment]
sample too slow for analysis during testing

**Pull request closed without merging**
