### PR TITLE
add QakBot sample to test the cape dynamic extractor

### PR DESCRIPTION
**Pull request by yelhamer**
this tests the CapeExtractor's ability to extract features from a sample's json report.

### CODE REVIEW

**Comment by yelhamer** [comment]
should we choose to continue testing the dynamic extractors functionality this way (as opposed to passing executables to them), we should configure the tests to not fail for a .json_ extension.

**Comment by mr-tz** [comment]
Right, please add the update to https://github.com/mandiant/capa-testfiles/blob/master/.github/check_sample_filenames.py (if needed).

I think the files should go into a dynamic directory and then use `<sandbox>_<hash>.json` for their name (or create a sandbox subdirectory?).

**Comment by williballenthin** [comment]
i've updated this PR to target branch `dynamic-feature-extractor` (new branch here). this way we can stage all the dynamic analysis changes, just like we're doing in the capa repo.

in the capa repo dynamic branch, we should update the capa-testfiles submodule to point to this new branch of testfiles.

**Comment by williballenthin** [comment]
image
lets compress the file with gzip and use the .json.gz file extension

**Comment by williballenthin** [comment]
agree with moritz, please use the path:

`dynamic/cape/<sha256>.json.gz`

**Review by williballenthin — APPROVED** [review]
thank you!

**Pull request merged**
