### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sara-rn**
.NET bundled file

### CODE REVIEW

**Comment by mr-tz** [comment]
Should this be detected as .NET sample? Does this run locally for 30 minutes or so as well?

**Comment by mr-tz** [comment]
Or should this be a limitation that we cannot analyze this properly (currently)?

**Comment by sara-rn** [comment]
hmm good point, the rest of the detections are meaningless. The main DLL is contained in the overlay section, I am happy to discuss this. I submitted 1 out of 2 rules to detect these

**Comment by sara-rn** [comment]
the problem is also that typically these files might be huge, more  than 100 MB. Just found this that is smaller.

**Comment by mr-tz** [comment]
For these huge files capa may not be the best tool as full analysis will likely take a while.

We could do something with the file level extractor of course to still identify these quickly and inform users though.

**Comment by sara-rn** [comment]
yes, I would vote for that, informing the user that it is a .NET bundled package. Some are typically more than 150 MB but only because of the overlay section. I suggest checking the PE Size vs the File Size. Let me know how we can identify these with the file level extractor.

**Comment by mr-tz** [comment]
We do not extract file vs. PE size currently. I've added a comment on the rule PR regarding namespace/directory for the limitation. If you look at the other limitation rules this one can hopefully be done similarly. Otherwise, we need to update the code slightly to inform users.

**Comment by sara-rn** [comment]
too slow, found another smaller sample

**Pull request closed without merging**
