### PR TITLE
Added test file

### PR DESCRIPTION
**Pull request by jaxxpnd**
Added test file for minifilter rule

### CODE REVIEW

**Comment by mr-tz** [comment]
Please add a valid file extension like other files in the repo.

**Comment by jaxxpnd** [comment]
Done

**Comment by mr-tz** [comment]
Ouh, sorry, needs to be lowercase :/

**Comment by jaxxpnd** [comment]
Not sure I follow? It is lowercase

**Comment by mr-tz** [comment]
Oh, my bad. A different file sneaked in there before.

**Comment by mr-tz** [comment]
Thank you!

**Pull request merged**
